const list = [
  {
    id: 1,
    title: "Apple AirTag",
    price: 189,
    img: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/713xuNx00oS._AC_SX679_.jpg",
    amount: 1,
  },
  {
    id: 2,
    title: "Yosemite Falls Scenery",
    price: 98,
    img: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/516bkWgM+xL._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 3,
    title: "The light we carry",
    author: "by Michelle Obama  | 25 November 2018",
    price: 83,
    img: "https://images-na.ssl-images-amazon.com/images/I/91MowzF+WZL._AC_UL210_SR195,210_.jpg",
    amount: 1,
  },
  {
    id: 4,
    title: "Fruit of the Loom Sweatshirt",
    price: 97,
    img: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/91aTSrL9fwS._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 5,
    title: "White Board 16inX12in",
    price: 49,
    img: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/61ZpKy9zMzL._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 6,
    title: "Kitchen Utensils Set",
    price: 35,
    img: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/814bNOiLBmL._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 7,
    title: "Himalayan Skin Care",
    price: 93,
    img: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/71wA-ZYRlIL._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 8,
    title: "Daffiner Cotton Down",
    price: 289,
    img: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/61mprLPAsZL._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 9,
    title: "Shaving Kit",
    price: 67,
    img: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/71XPtzLd3lL._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 10,
    title: "Nike Academy Team Football",
    price: 86,
    img: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/61Pvhbi+zlL._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 11,
    title: "Portable Air Conditioner",
    price: 120,
    img: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/61qOWR65DUL._AC_UY218_.jpg",
    amount: 1,
  },
  {
    id: 12,
    title: "Car Emergency Kit",
    price: 157,
    img: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81Dlg2ZmJ-L._AC_UL320_.jpg",
    amount: 1,
  },
];

export default list;
